version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  postgres-test:
    restart: always
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
